# Generated by Django 3.1.3 on 2020-12-15 06:33

from __future__ import absolute_import

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="can_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bank",
            name="bank",
            field=models.CharField(
                choices=[
                    ("access_bank", "Access Bank"),
                    ("citibank", "Citibank"),
                    ("dynamic_standard_bank", "Dynamic Standard Bank"),
                    ("ecobank_ngr", "Ecobank Nigeria"),
                    ("fidelity_bank_ngr", "Fidelity Bank Nigeria"),
                    ("fbn", "First Bank of Nigeria"),
                    ("fcmb", "First City Monument Bank"),
                    ("gtb", "Guaranty Trust Bank"),
                    ("hb", "Heritage Bank"),
                    ("jz", "Jaiz Bank"),
                    ("keystone", "Keystone Bank"),
                    ("providus", "Providus Bank"),
                    ("polaris", "Polaris Bank"),
                    ("stanbic", "Stanbic IBTC Bank Nigeria"),
                    ("standard_chartered", "Standard Chartered Bank"),
                    ("sterling", "Sterling Bank"),
                    ("suntrust", "Suntrust Bank Nigeria"),
                    ("union_bank", "Union Bank of Nigeria"),
                    ("uba", "United Bank for Africa"),
                    ("unity_bank", "Unity Bank"),
                    ("wema_bank", "Wema Bank"),
                    ("zenith_bank", "Zenith Bank"),
                ],
                default="access_bank",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
