# Generated by Django 3.1.3 on 2020-12-17 03:57

from __future__ import absolute_import

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_auto_20201215_0633"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="updated_by",
        ),
    ]
