# Generated by Django 3.1.3 on 2020-12-22 11:47

from __future__ import absolute_import

import dirtyfields.dirtyfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_auto_20201218_0524"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "minimum_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maximum_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("return_on_investmentent", models.PositiveIntegerField()),
                ("days", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
