# Generated by Django 3.1.3 on 2020-12-17 11:25

from __future__ import absolute_import

import dirtyfields.dirtyfields
from django.db import migrations, models

import dashboard.models
import finance.validators


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_remove_bank_updated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentPackage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("Roi", models.IntegerField()),
                (
                    "duration",
                    models.PositiveIntegerField(verbose_name="Duration in days"),
                ),
                ("working_days_only", models.BooleanField(default=True)),
                ("payment_duration", models.PositiveIntegerField()),
                ("minimum_amount", models.DecimalField(decimal_places=2, max_digits=9)),
                ("maximum_amount", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "account_number",
                    models.CharField(
                        help_text="Enter your 10 digit account number",
                        max_length=10,
                        validators=[finance.validators.validate_account_number],
                    ),
                ),
            ],
            bases=(
                dirtyfields.dirtyfields.DirtyFieldsMixin,
                models.Model,
                dashboard.models.TimeStampMixin,
            ),
        ),
    ]
