# Generated by Django 3.1.3 on 2020-12-22 22:35

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="codename",
            field=models.CharField(default="ovviy_min", max_length=30),
            preserve_default=False,
        ),
    ]
