# Generated by Django 3.1.3 on 2020-12-22 22:40

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_package_codename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="codename",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
