# Generated by Django 3.1.3 on 2020-12-18 05:06

from __future__ import absolute_import

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_investmentpackage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investmentpackage",
            name="account_number",
        ),
    ]
