# Generated by Django 3.1.3 on 2020-12-22 22:41

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_auto_20201222_2240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
