# Generated by Django 3.1.3 on 2020-12-18 05:07

from __future__ import absolute_import

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_remove_investmentpackage_account_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investmentpackage",
            old_name="Roi",
            new_name="roi",
        ),
    ]
