# Generated by Django 3.1.3 on 2020-12-26 06:46

from __future__ import absolute_import

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="package",
            field=models.ForeignKey(
                max_length=20,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="finance.package",
            ),
        ),
    ]
