# Generated by Django 3.1.3 on 2020-12-29 00:06

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_investment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="status",
            field=models.CharField(
                choices=[
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("running", "Running"),
                    ("success", "Success"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
