# Generated by Django 3.1.3 on 2020-12-29 17:28

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_auto_20201229_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="roischedule",
            name="roi",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
