# Generated by Django 3.1.3 on 2020-12-29 17:29

from __future__ import absolute_import

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_roischedule_roi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roischedule",
            old_name="roi",
            new_name="roi_amount",
        ),
    ]
