# Generated by Django 3.1.3 on 2021-01-04 11:58

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_auto_20201229_1729"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="for_package",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="investment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("transfer", "Transfer"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roischedule",
            name="action",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("transfer", "Transfer"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roischedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("transfer", "Transfer"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
