# Generated by Django 3.1.5 on 2021-01-05 17:34

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_auto_20210104_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="level",
            field=models.CharField(
                choices=[
                    ("fresher", "Fresher"),
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                ],
                default="silver",
                max_length=30,
            ),
        ),
    ]
