# Generated by Django 3.1.5 on 2021-01-18 11:16

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_auto_20210109_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
