# Generated by Django 3.1.5 on 2021-01-21 12:29

from __future__ import absolute_import

from django.db import migrations, models

import finance.validators


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0017_package_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="days",
            field=models.IntegerField(validators=[finance.validators.validate_number]),
        ),
        migrations.AlterField(
            model_name="package",
            name="maximum_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[finance.validators.validate_number],
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="minimum_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[finance.validators.validate_number],
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[finance.validators.validate_alphanumeric],
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="return_on_investmentent",
            field=models.PositiveIntegerField(
                validators=[finance.validators.validate_number]
            ),
        ),
    ]
