# Generated by Django 3.1.5 on 2021-02-07 10:12

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0021_auto_20210207_0138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banks",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="banks",
            name="slug",
            field=models.SlugField(max_length=15, unique=True),
        ),
    ]
