# Generated by Django 3.1.5 on 2021-02-07 10:13

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0022_auto_20210207_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banks",
            name="country",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="banks",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="banks",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="banks",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
