# Generated by Django 3.1.5 on 2021-02-07 10:25

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0024_add_paystack_banks_and _codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="bank",
            field=models.CharField(default="access-bank", max_length=30),
        ),
    ]
