# Generated by Django 3.1.5 on 2021-02-10 05:58

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0025_auto_20210207_1025"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="recipient_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
