# Generated by Django 3.1.5 on 2021-02-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0026_bank_recipient_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="bank",
        ),
    ]
