# Generated by Django 3.1.5 on 2021-01-09 19:14

from __future__ import absolute_import

import django.contrib.auth.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageCenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("subject", models.CharField(max_length=30)),
                ("city", models.CharField(blank=True, max_length=30, null=True)),
                ("message", models.CharField(max_length=30)),
                ("read", models.BooleanField(default=False)),
                (
                    "to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model),
        ),
    ]
