# Generated by Django 3.1.5 on 2021-01-09 19:20

from __future__ import absolute_import

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagecenter",
            name="city",
        ),
    ]
