# Generated by Django 3.1.5 on 2021-01-09 20:19

from __future__ import absolute_import

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0002_remove_messagecenter_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagecenter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="messagecenter",
            name="to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="messagecenter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
