# Generated by Django 3.1.5 on 2021-01-12 08:43

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_auto_20210109_2019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagecenter",
            name="subject",
            field=models.CharField(max_length=120),
        ),
    ]
