# Generated by Django 3.1.5 on 2021-01-12 09:33

from __future__ import absolute_import

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0004_auto_20210112_0843"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagecenter",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagecenter",
            name="sent_from_admin",
            field=models.BooleanField(default=False),
        ),
    ]
