# Generated by Django 3.1.5 on 2021-01-13 13:57

from __future__ import absolute_import

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0005_auto_20210112_0933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagecenter",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_msgs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
