# Generated by Django 3.1.5 on 2021-02-13 00:03

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditing", "0002_auto_20210212_2356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelchange",
            name="changes",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
