# Generated by Django 3.1.5 on 2021-02-13 00:12

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditing", "0003_auto_20210213_0003"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelchange",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
