# Generated by Django 3.1.5 on 2021-02-13 00:30

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditing", "0004_modelchange_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelchange",
            name="colour_code",
            field=models.CharField(
                choices=[
                    ("blue", "blue"),
                    ("green", "green"),
                    ("purple", "purple"),
                    ("yellow", "yellow"),
                ],
                default="yellow",
                max_length=12,
            ),
            preserve_default=False,
        ),
    ]
