# Generated by Django 3.1.3 on 2020-12-15 13:30

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20201213_1546"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="address2",
            new_name="area",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
