# Generated by Django 3.1.3 on 2020-12-17 03:57

from __future__ import absolute_import

from django.db import migrations, models

import paytime.utils


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20201215_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[paytime.utils.validate_ng_mobile_number],
            ),
        ),
    ]
