# Generated by Django 3.1.5 on 2021-01-06 16:58

from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20210106_1648"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
